### ISSUE TITLE
Building a client environment

### ISSUE THREAD

**Issue by jp-knj** [jp-knj/demo-timer#1]
## Tasks
- [x] Add React, React dom
- [x] Add TypeScript 
- [x] Add Webpack, Babel
- [x] Add prettier, eslint
